Repository Yothu/reservify-front-end, pull requests merged in 2022-06, with the labels that each got.

#25 Create the Sidebar
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/components/Sidebar/SidebarData.js
  src/images/logo.png
  src/index.css
  src/pages/Hotels.js
  src/pages/Hotels.module.css
Labels: enhancement

#27 Add Signup Page
  package-lock.json
  package.json
  src/App.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/components/Sidebar/SidebarData.js
  src/components/Signup/SignupForm.jsx
  src/components/Ui/Button.jsx
  src/components/Ui/Button.module.css
  src/components/Ui/ErrorMsg.jsx
  src/images/undraw-svg/green-register.svg
  src/images/undraw-svg/green-welcome.svg
  src/images/undraw-svg/register.svg
  src/images/undraw-svg/welcome.svg
  src/index.css
  src/pages/signup/Signup.jsx
Labels: enhancement

#28 Add splash screen
  .gitignore
  .stylelintrc.json
  package-lock.json
  package.json
  src/App.js
  src/assets/fonts/Reflex_Black.ttf
  src/assets/images/double-bar-icon-2.png
  src/assets/images/hotel-menu.jpg
  src/assets/images/room-1.jpg
  src/assets/images/search-icon.png
  src/index.css
  src/index.js
  src/pages/Registration/SplashScreen.js
  src/pages/Registration/SplashScreen.module.css
Labels: enhancement

#29 Add Splash screen
  .eslintrc.json
  package.json
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/components/SplashScreen/AuthButtons/AuthButtons.js
  src/components/SplashScreen/AuthButtons/AuthButtons.module.css
  src/components/SplashScreen/MainImage/MainImage.js
  src/components/SplashScreen/MainImage/MainImage.module.css
  src/components/SplashScreen/TopMenu/TopMenu.js
  src/components/SplashScreen/TopMenu/TopMenu.module.css
  src/components/Ui/Button.jsx
  src/pages/Hotels.js
  src/pages/Hotels.module.css
  src/pages/Registration/SplashScreen.js
  src/pages/Registration/SplashScreen.module.css
Labels: enhancement

#26 Add login page
  package.json
  src/App.js
  src/pages/registration/LogIn.js
  src/pages/registration/SplashScreen.js
  src/pages/registration/SplashScreen.module.css
  src/pages/registration/signup/Signup.jsx
  src/pages/registration/signup/Signup.module.css
  src/tests/LogIn.test.js
Labels: enhancement, testing

#31 Add hotel page
  src/App.js
  src/components/AddHotel/AddHotelForm.js
  src/components/Sidebar/SidebarData.js
  src/pages/admin/addHotel/addHotel.js
  src/pages/registration/SplashScreen.js
Labels: enhancement

#32 Create Main Page
  src/App.js
  src/components/AddHotel/AddHotelForm.js
  src/components/Sidebar/Sidebar.jsx
  src/components/main/HotelCard.jsx
  src/components/main/HotelCard.module.css
  src/components/main/HotelsData.js
  src/components/main/MainSlider.jsx
  src/components/main/MainSlider.module.css
  src/pages/main/Main.jsx
  src/pages/main/Main.module.css
  src/pages/registration/signup/Signup.module.css
Labels: enhancement

#33 Create delete hotel page, add basic hotel reducer
  src/App.js
  src/components/DeleteHotel/DeleteHotelList.js
  src/components/DeleteHotel/DeleteHotelList.module.css
  src/components/DeleteHotel/DeleteHotelListRow.js
  src/components/Sidebar/SidebarData.js
  src/pages/admin/addHotel/AddHotel.js
  src/pages/admin/deleteHotel/DeleteHotel.js
  src/redux/hotels/hotel-slice.js
  src/redux/store.js
Labels: enhancement

#35 Feature/hotel details
  package.json
  src/App.js
  src/components/Amenities.js
  src/components/Sidebar/Sidebar.jsx
  src/pages/HotelDetails.js
  src/pages/Hotels.js
  src/styles/HotelDetails.scss
Labels: enhancement

#38 Feature/page reservations
  package.json
  src/App.js
  src/components/Sidebar/SidebarData.js
  src/pages/MyReservations.js
Labels: enhancement

#34 Auth: User Register
  package.json
  src/App.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/SidebarData.js
  src/components/Signup/SignupForm.jsx
  src/components/main/MainSlider.jsx
  src/pages/registration/LogIn.js
  src/pages/registration/signup/Signup.jsx
  src/redux/auth/auth-services.js
  src/redux/auth/auth-slice.js
  src/redux/counter/counter-slice.js
  src/redux/hotels/hotel-services.js
  src/redux/hotels/hotel-slice.js
  src/redux/store.js
  src/tests/LogIn.test.js
Labels: enhancement

#43 Final styling
  src/components/Amenities.js
  src/components/Reserve/ReserveForm.jsx
  src/pages/HotelDetails.js
  src/pages/MyReservations.js
  src/pages/MyReservations.module.css
  src/styles/HotelDetails.scss
Labels: enhancement

#41 Documentation
  README.md
Labels: documentation

#46 Review Fixes
  src/components/Amenities.js
  src/components/main/HotelCard.module.css
  src/components/main/MainSlider.jsx
  src/index.css
  src/pages/HotelDetails.js
  src/pages/main/Main.jsx
  src/pages/main/Main.module.css
  src/styles/HotelDetails.scss
Labels: enhancement
